# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.org3.ticketChain.sfeir.lu:
  peer1.org3.ticketChain.sfeir.lu:

networks:
  byfn:

services:

  peer0.org3.ticketChain.sfeir.lu:
    container_name: peer0.org3.ticketChain.sfeir.lu
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.ticketChain.sfeir.lu
      - CORE_PEER_ADDRESS=peer0.org3.ticketChain.sfeir.lu:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.ticketChain.sfeir.lu:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.ticketChain.sfeir.lu:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.ticketChain.sfeir.lu:13051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer0.org3.ticketChain.sfeir.lu/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer0.org3.ticketChain.sfeir.lu/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.ticketChain.sfeir.lu:/var/hyperledger/production
    ports:
      - 13051:13051
    networks:
      - byfn

  peer1.org3.ticketChain.sfeir.lu:
    container_name: peer1.org3.ticketChain.sfeir.lu
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.ticketChain.sfeir.lu
      - CORE_PEER_ADDRESS=peer1.org3.ticketChain.sfeir.lu:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.ticketChain.sfeir.lu:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.ticketChain.sfeir.lu:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.ticketChain.sfeir.lu:14051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer1.org3.ticketChain.sfeir.lu/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer1.org3.ticketChain.sfeir.lu/tls:/etc/hyperledger/fabric/tls
        - peer1.org3.ticketChain.sfeir.lu:/var/hyperledger/production
    ports:
      - 14051:14051
    networks:
      - byfn


  Org3cli:
    container_name: Org3cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=Org3cli
      - CORE_PEER_ADDRESS=peer0.org3.ticketChain.sfeir.lu:13051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer0.org3.ticketChain.sfeir.lu/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer0.org3.ticketChain.sfeir.lu/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.ticketChain.sfeir.lu/peers/peer0.org3.ticketChain.sfeir.lu/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.ticketChain.sfeir.lu/users/Admin@org3.ticketChain.sfeir.lu/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./org3-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/sfeir.ticketChain.sfeir.lu:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sfeir.ticketChain.sfeir.lu
        - ./crypto-config/peerOrganizations/ticketMaster.ticketChain.sfeir.lu:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ticketMaster.ticketChain.sfeir.lu
        - ./crypto-config/peerOrganizations/bankRoute.ticketChain.sfeir.lu:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bankRoute.ticketChain.sfeir.lu
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org3.ticketChain.sfeir.lu
      - peer1.org3.ticketChain.sfeir.lu
    networks:
      - byfn
