# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.ticketChain.sfeir.lu:
  orderer3.ticketChain.sfeir.lu:
  orderer4.ticketChain.sfeir.lu:
  orderer5.ticketChain.sfeir.lu:

networks:
  byfn:

services:

  orderer2.ticketChain.sfeir.lu:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.ticketChain.sfeir.lu
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer2.ticketChain.sfeir.lu/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer2.ticketChain.sfeir.lu/tls/:/var/hyperledger/orderer/tls
        - orderer2.ticketChain.sfeir.lu:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.ticketChain.sfeir.lu:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.ticketChain.sfeir.lu
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer3.ticketChain.sfeir.lu/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer3.ticketChain.sfeir.lu/tls/:/var/hyperledger/orderer/tls
        - orderer3.ticketChain.sfeir.lu:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.ticketChain.sfeir.lu:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.ticketChain.sfeir.lu
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer4.ticketChain.sfeir.lu/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer4.ticketChain.sfeir.lu/tls/:/var/hyperledger/orderer/tls
        - orderer4.ticketChain.sfeir.lu:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.ticketChain.sfeir.lu:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.ticketChain.sfeir.lu
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer5.ticketChain.sfeir.lu/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ticketChain.sfeir.lu/orderers/orderer5.ticketChain.sfeir.lu/tls/:/var/hyperledger/orderer/tls
        - orderer5.ticketChain.sfeir.lu:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
